### ISSUE TITLE
remove CVs

### ISSUE THREAD

**Issue by gioman** [pcav/faunalia-website#187]
this

http://www.faunalia.eu/en/pdf/Neves_CV_en.pdf
http://www.faunalia.eu/en/pdf/Neves_CV_it.pdf
http://www.faunalia.eu/en/pdf/Neves_CV_pt.pdf

and this

http://www.faunalia.eu/en/pdf/Manghi_CV_en.pdf
http://www.faunalia.eu/en/pdf/Manghi_CV_it.pdf
http://www.faunalia.eu/en/pdf/Manghi_CV_pt.pdf

must be removed, they still show upon google searches.

**Comment by pcav** [comment]
Fixed
