### ISSUE TITLE
Translated items in news section

### ISSUE THREAD

**Issue by pcav** [pcav/faunalia-website#189]
They appear in green, because `<p class="first">` is added automatically.

**Comment by tomchadwin** [comment]
Can you post a link here to a page which has the problem?

**Comment by pcav** [comment]
This is visible in the index page:
http://www.faunalia.eu/it/ is OK
http://www.faunalia.eu/en/ shows the big green text

**Comment by tomchadwin** [comment]
I can't figure this one out. I don't know the process or the components. Given that the problem is an unwanted HTML element, I guess this has to be the result of the `sphinx_bootstrap_theme` process.

I suppose a test would be to swap the first and second news items in the source file. This would tell us whether it is something intrinsic to the content which causes the error, or whether it is just the position. I presume the latter, since I can see no difference in the source between items 1 and 2.

**Comment by tomchadwin** [comment]
Or it's caused by the translation process. But I can see no difference in the source and translation which might lead to the addition of the unwanted tag.

**Comment by tomchadwin** [comment]
Would you be happy for me to open an issue on https://github.com/ryan-roemer/sphinx-bootstrap-theme/, giving details of this instance of the issue?

**Comment by pcav** [comment]
Unsure about that: more likely culprit to me is either sphinx or sphinx-intl

**Comment by tomchadwin** [comment]
Yes, on second thoughts, you are correct. Looking at Sphinx now.

**Comment by tomchadwin** [comment]
OK, forget the fact that it is first. The problem occurs multiple times on the page:

- Why Faunalia courses are better for you
- Need 3D in QGIS? A glimpse of the future
- Another nice plugin: Historical maps
- Big plans for next QGIS
- An easier and safer life for QGIS plugin writer
- Paolo Cavallini appointed as QGIS co-chair
- Let us hear your voice: a survey on QGIS usage
- New PostGIS version
- Really Fast Fourier filter for rasters in QGIS
- More background maps in QGIS
- Opinions on QGIS: today and the future
- New QGIS Long Term Release
- Yet another interesting QGIS plugin: Cartograms

So what is different about those items in `index.rst` to the other items?

**Comment by pcav** [comment]
Possibly because they are on a list? 

* xyz

**Comment by tomchadwin** [comment]
Related, unanswered SO question:

http://stackoverflow.com/questions/19295399/why-is-sphinx-doc-wrapping-numbered-list-items-in-p-when-i-insert-a-figure

Also Github issue:

https://github.com/snide/sphinx_rtd_theme/issues/119

Seems to occur with nested `UL`s.

**Comment by tomchadwin** [comment]
Given no Sphinx answer to the two links posted above, I guess we just have to live with the extra `p` tag and hack the CSS. I'll look at that now.

**Comment by pcav** [comment]
so possibly one could change the css (I do not really need UL, it was a hack to display text in a more reasonable way than without). Feel free to change.

**Comment by tomchadwin** [comment]
If you can lose the UL, great (removing extraneous markup always A Good Thing). Otherwise, try adding the following extra CSS:

```CSS
#news li > p.first {
    font-size: 16px;
    color: #333333;
    text-align: left;
}
``

**Comment by pcav** [comment]
Perfect if we remove the ul. However, the css should be updated to show reasonable text (have you seen how it looks like without?).

**Comment by tomchadwin** [comment]
Ah, OK. Try removing the UL/LIs, and instead of the CSS above, add:

```CSS
#news p {
    color: #333;
    text-align: left;
    font-size: 16px;
    padding-left: 0.25em;
    padding-right: 0.25em;
}
```

**Comment by pcav** [comment]
I have to put it in _static/faunalia.css_t I suppose

**Comment by tomchadwin** [comment]
And then link to it here:

https://github.com/pcav/faunalia-website/blob/master/conf.py#L107

However, I don't know if that **adds** to the CSS, or replaces it entirely. Try it in your test environment first, and see what happens.

**Comment by pcav** [comment]
hm, _static/faunalia.css_t is already used, but I do not know the syntax to add different styles

**Comment by pcav** [comment]
Published, great.
