### ISSUE TITLE
On small screens, the lang switch is hidden

### ISSUE THREAD

**Issue by pcav** [pcav/faunalia-website#86]

**Comment by tomchadwin** [comment]
Can you post a link here to a page which has the problem?

**Comment by pcav** [comment]
Any page, e.g. http://www.faunalia.eu/en/
Shrink the window and you'll see.

**Comment by tomchadwin** [comment]
Chrome/Android: the translate drop-down is in the hamburger menu, but you have to drag to reveal it. Is that what others see?

**Comment by tomchadwin** [comment]
In fact, it's even briefly visible, and then the menu truncates to hide it. Do others see this?

**Comment by pcav** [comment]
Yes, exactly.

**Comment by pcav** [comment]
Unsure this is an upstream problem with bootstrap-sphinx theme though.

**Comment by pcav** [comment]
Fixed, thanks.
